---
- name: Clean up Docker
  hosts: all
  become: yes  # Ensures that the task runs with sudo
  collections:
    - community.docker
  tasks:
    - name: Install requests python package
      pip:
        name: requests
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Run Docker system prune
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
