---
- name: Clean up Docker
  hosts: all
  become: yes  # Ensures that the task runs with sudo
  collections:
	  - community.docker
  tasks:
    - name: Run Docker system prune
      community.docker.docker_prune:
    		containers: yes
    		images: yes
    		images_filters:
    		  dangling: false
    		networks: yes
    		volumes: yes
    		builder_cache: yes
